apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: rag-ingress

spec:

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:

          service:
            name: enterprise-rag-service

            port:
              number: 80